### PR TITLE
[Improved] Fixing crash when rss feed has no attributes in <rss> tag

### PR DESCRIPTION
**Pull request by fmalk**
This PR implements the same code as of https://github.com/bobby-brennan/rss-parser/pull/65 from @ricardoekm , with some improvements:

- Slight difference at https://github.com/bobby-brennan/rss-parser/pull/65/commits/83600cf6c5d94e90ade667aa2c5e688e815f4cb8
- Another bugfix resulting from missing `result.rss.$` at parser.js at line 152
- The mentioned RSS causing the crash was added to a new test (Travis is already passing)

Anyways, thanks @ricardoekm for already providing the codefix (I was trying to parse the same feed), so my contribution is mostly providing the passing test.
@bobby-brennan you should check you're confortable with the way we assume RSS 0.9 in case of missing metadata. I'd assume RSS 2.0, but @ricardoekm implemented as 0.9 and I went with it.

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Thanks! Can you just revert `package.json` and `package-lock.json`? I'll update these when I release.

Other than that looks great!

**Comment by fmalk** [comment]
@bobby-brennan will do.
actually, I'll submit an update on this PR, something that @ricardoekm hinted as well - a way to determine which RSS version should be default. I'll include it as a Parser option.
I'll push that and revert the package.json.

**Comment by fmalk** [comment]
@bobby-brennan I think this version is solid.
I reverted package.json and lock to your current master. However, most dependencies have several updates, and updating doesn't break any tests. So I recommend regenerating the lock with up-to-date versions, but I'll leave it to you.

What I did here was to enable a new option:
```
let parser = new Parser({
  defaultRSS: 2.0
});
```

If not provided, a broken feed will crash, same as before, but if set, the parser will use the appropriate `buildRSSX()` method.
I provided a new test to check for this crash, and also added a README section telling about this option.
That's it! I hope it'll help other people.

**Comment by bobby-brennan** [comment]
Looks great! Thanks a bunch for the contribution.

**Comment by fmalk** [comment]
@bobby-brennan I realized there's still a new build to be updated, do you mind to create one with my merged code?

**Comment by bobby-brennan** [comment]
I've published your change as 3.5.0, and some dependency updates in 3.5.1

**Comment by fmalk** [comment]
@bobby-brennan I meant the distribution files in the `/dist` folder, those didnt't seem to have been updated

**Comment by bobby-brennan** [comment]
Whoops! Good catch - the dist was updated in 3.5.2

**Pull request merged**
