### PR TITLE
Fix #35.

### LINKED ISSUE #35: Unhandled error when decorating iTunes result without an image URL
`parser.parseURL()` throws the following error for podcast rss feeds that don't have an image URL:
```
Cannot read property 'href' of undefined
```

This happens occasionally and I've got about 10 podcasts for which I can reproduce. I've forked and fixed by just not adding an image property to `itunes` during decoration. I'll send a PR shortly to fix if it looks 👌 .

### PR DESCRIPTION
**Pull request by coderigo**

### CODE REVIEW

**Comment by coderigo** [comment]
Ah, yes. Good point. No problems. Will do in a bit.

**Comment by coderigo** [comment]
Done and pushed. Tests seem 👌 .

**Comment by bobby-brennan** [comment]
Published as v2.10.4

Thanks for the contribution!

**Comment by coderigo** [comment]
👍  Quick follow up, is `v2.10.4` published to npm? It's still showing `2.10.3` and `npm i` doesn't seem to think `2.10.4` is a valid version number.

**Comment by bobby-brennan** [comment]
Whoops, never ran `npm publish` :) should be good now

**Comment by coderigo** [comment]
Yup. all good. Thanks.

**Pull request merged**
