### PR TITLE
Added support for arrays of custom fields

### PR DESCRIPTION
**Pull request by AttackTheDarkness**
The previous implementation would take the first instance of a custom field and return that, which is definitely the most common case... but not the only one. I extended the custom field syntax to allow an options object. You can now pass a `keepArray` option to return an array of nodes (a la the default `categories` behavior).

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Looks good! Mind adding a note to the README?

You can also revert package-lock.json and the dist/ files - I will update those as part of the release process.

Thanks for the contribution!

**Comment by AttackTheDarkness** [comment]
Done.

**Comment by bobby-brennan** [comment]
Perfect, thanks!

**Comment by bobby-brennan** [comment]
Released as 3.1.0

**Pull request merged**
