### PR TITLE
Built out basic ability to parse provided URL

### PR DESCRIPTION
**Pull request by andjosh**
Mainly wanted it on the client side, but stubbed it out on the server, too.

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Thanks! Looks like I forgot to implement it :)

The client side code is actually generated by browserify, so I just implemented your changes to index.js and regenerated. The updated versions should be available on bower and npm.

**Comment by andjosh** [comment]
That's cool, but I don't think you'll want to use the node-request library on the client side.

It adds ~57k lines of code to the final `/dist` version of rss-parser - pushing the file up around 2mb of load. My proposed change only adds ~25 lines of code.

But I do understand that you want to auto-generate the client lib with Browserify. Up to you!

**Comment by bobby-brennan** [comment]
Good point. I have this code running on both client and server and need them to stay in sync, but I switched to using http(s) instead of request, which took the size from ~1900kB to 400kB

**Comment by andjosh** [comment]
Nice

**Pull request closed without merging**
