### PR TITLE
Fix for missing image in itunes:image on item

### PR DESCRIPTION
**Pull request by jbjorge**
Hi!
Thanks for creating an easy to use parser.
It currently doesn't pick up itunes:image in items, so I added that. I'm a bit under time pressure, so I'm not sure my implementation is the best.

Br
Jay

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Thanks for the fix!

Is the only valid attribute on itunes:image the href tag?  If not (or if you're not certain), maybe we should set the image field to an object, i.e.

```js
{
  itunes: {
    image: {
      href: "http://example.com"
    }
  }
}
```

**Comment by jbjorge** [comment]
I'm not quite sure, so doing it like you proposed is definitely the best way since it provides flexibility for future changes without breaking the api.
I'll update the PR in a few hours when I get some time off. Thanks for the stellar quick reply!

**Comment by jbjorge** [comment]
I checked the [spec](https://lists.apple.com/archives/syndication-dev/2005/Nov/msg00002.html#_Toc526931685), and `<itunes:image>` will only have a href-attribute. I added a check so it won't add .image if href is not present on the node.

**Comment by bobby-brennan** [comment]
Perfect, thanks! I'll cut a release once PR #23 is merged.

**Pull request merged**
